# Override generated by sandbox-vibe.
# Edit only with full understanding — this file may be regenerated by 'sandbox-vibe init'.

services:
  sandbox:
    image: sandbox-vibe:latest
    build:
      context: .
      dockerfile: Dockerfile.sandbox.override
    volumes:
${volumesBlock}

    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        set -o pipefail

        mkdir -p ~/.claude
        cat > ~/.claude/settings.json << 'EOF'
        {
          "permissions": {
            "additionalDirectories": ${additionalDirsBlock}
          },
          "enabledPlugins": ${enabledPluginsBlock}
        }
        EOF

        if [ ! -f ~/.claude/.${marker} ]; then
          BOOT_LOG=/tmp/sandbox-bootstrap.log
          : > "$$BOOT_LOG"
          chmod 600 "$$BOOT_LOG"
          echo "[sandbox] First run: installing marketplaces, plugins and MCPs..."

${marketplacesBlock}

          for p in \
${pluginLoopBlock}; do
            echo "[sandbox] install: $$p"
            claude plugin install "$$p" >>"$$BOOT_LOG" 2>&1
          done
${mcpsBlock}
          touch ~/.claude/.${marker}
          echo "[sandbox] Bootstrap done. Log at $$BOOT_LOG (chmod 600)."
        fi

        if [ -t 0 ]; then
          exec claude --dangerously-skip-permissions
        else
          echo "[sandbox] No interactive TTY; exiting after bootstrap. Use 'docker compose ... run --rm sandbox' in a terminal."
        fi
    command: []

volumes:
  ${projectSlug}-sandbox-home:
