# Override layer generated by sandbox-vibe.
# Edit only with full understanding — this file may be regenerated by 'sandbox-vibe init'.

FROM sandbox-vibe-base:latest

USER root

# Always: npm + Claude Code
RUN npm install -g npm@latest \
 && npm install -g @anthropic-ai/claude-code@latest

# vibe-render:stackBlock

USER sandbox

# Useful env vars when .NET is installed (silences extra noise).
# Keeping them without .NET causes no side effect.
ENV DOTNET_NOLOGO=1 \
    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_ROOT=/usr/share/dotnet
